image: WMF 5
version: 1.0.0 (Build {build})

install:
  - cmd: GitVersion /output buildserver
  - ps: .\install.ps1 -ErrorAction Stop -InformationAction Continue -Verbose

build_script:
  - cmd: make

test_script:
  - cmd: make test --keep-going

before_deploy:
  - ps: >-
      & GitReleaseNotes . /OutputFile ReleaseNotes.md;
      ${env:release_description} = ( Get-Content -LiteralPath ReleaseNotes.md -Encoding UTF8 ) -join "`n";

deploy:
  - provider: Environment
    name: GitHub-Releases
    description: $(release_description)
    artifact: signcode.install
    on:
      branch: master
      #appveyor_repo_tag: true
  - provider: Environment
    name: Chocolatey
    artifact: signcode.install
    on:
      branch: master
      #appveyor_repo_tag: true
