image: WMF 5
version: 1.0.0 (Build {build})

init:
  - cmd: echo %PATH%
  - cmd: set PATH=%PATH%;%ProgramFiles%/AppVeyor/BuildAgent
  - cmd: echo %PATH%

branches:
  except:
    - /^modules\/.*$/

install:
  - cmd: GitVersion /output buildserver
  - ps: .\install.ps1 -ErrorAction Stop -InformationAction Continue -Verbose

build_script:
  - cmd: make

before_test: 
  - cmd: openssl pkcs12 -in sign/certificate/cert.pfx -passin pass:%CODE_SIGNING_CERTIFICATE_PASSWORD% -nokeys -out sign/certificate/cert.cer
  - ps: Import-Certificate -FilePath 'sign/certificate/cert.cer' -CertStoreLocation 'Cert:\LocalMachine\TrustedPublisher' -Verbose
  - cmd: openssl pkcs12 -in sign/certificate/cert.pfx -passin pass:%CODE_SIGNING_CERTIFICATE_PASSWORD% -nokeys -cacerts -out sign/certificate/CA.cer
  - ps: Import-Certificate -FilePath 'sign/certificate/CA.cer' -CertStoreLocation 'Cert:\LocalMachine\AuthRoot' -Verbose

test_script:
  - cmd: make test --keep-going

before_deploy:
  - ps: >-
      & GitReleaseNotes . /OutputFile ReleaseNotes.md;
      ${env:release_description} = ( Get-Content -LiteralPath ReleaseNotes.md -Encoding UTF8 ) -join "`n";

deploy:
  - provider: Environment
    name: GitHub-Releases
    description: $(release_description)
    artifact: package
    on:
      branch: master
      #appveyor_repo_tag: true
  - provider: Environment
    name: Chocolatey
    artifact: package
    on:
      branch: master
      #appveyor_repo_tag: true
